### ISSUE TITLE
 lorank.service: main process exited, code=exited, status=1

### ISSUE THREAD

**Issue by ajreisp** [Ideetron/Lorank#12]
My router do not start. I have already make an update but he only start the 1st time after reboot. After a few minutes he stop.

root@lorank8:~/lorank8v1# systemctl status lorank.service
lorank.service - Lorank activation
          Loaded: loaded (/lib/systemd/system/lorank.service; enabled)
          Active: activating (auto-restart) (Result: exit-code) since Wed, 09 Nov 2016 20:52:09 +0000; 3s ago
         Process: 2762 ExecStart=/root/lorank8v1/start (code=exited, status=1/FAILURE)
          CGroup: name=systemd:/system/lorank.service

Nov 09 20:52:09 lorank8 lorank8v1[2762]: Starting the Poly packet forwarder.
Nov 09 20:52:09 lorank8 lorank8v1[2762]: *** Poly Packet Forwarder for Lora Gateway ***

**Comment by devlaam** [comment]
Hi, this can have many causes of course. Without a larger part of the log file it is hard to judge what is going on. It could even be a hardware failure, although this is unlikely. The best thing to do right now is send an email to Ideetron with your complaint with a larger part of the log file, typically a thousand lines, or simply zip the whole file and attach it to the email. Do not post your file here for it may reveal privacy sensitive information. Please include the version you are running right now, and the info of /etc/dogtag and uname -a.

**Comment by barthiddink** [comment]
Use info@ideetron.nl.

Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Ruud Vlaming notifications@github.com Datum: 10-11-16  21:46  (GMT+01:00) Aan: Ideetron/Lorank Lorank@noreply.github.com Onderwerp: Re: [Ideetron/Lorank] lorank.service: main process exited, code=exited, status=1 (#12) 
Closed #12.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Ideetron/Lorank","title":"Ideetron/Lorank","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Ideetron/Lorank"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #12."}],"action":{"name":"View Issue","url":"https://github.com/Ideetron/Lorank/issues/12#event-855083194"}}}
