### ISSUE TITLE
Base OS version

### ISSUE THREAD

**Issue by jpmeijers** [Ideetron/Lorank#16]
On which OS should this installer be run. I see 4 directories with a substring of the MD5 of the dogtag.

The best I can find is:
```
debian@beaglebone:~$ echo "BeagleBoard.org Debian Image 2016-05-13" | md5sum
9e75c16c53c5f324030c545e70f26558  -
```

So I believe `BeagleBoard.org Debian Image 2016-05-13` is one possible base OS, but what are the other options? Anything newer than 2016?

**Comment by devlaam** [comment]
Yes, this is the latest official supported version. You can always try a later version by simply copying the latest and adjusting the md5 of the dogtag accordingly. If it works, nice, if not, usually there are just a few small changes to make.

**Comment by bueli** [comment]
Started with fresh installation on latest BBB Image [Debian 9.5 2018-10-07 4GB SD IoT](https://debian.beagleboard.org/images/bone-debian-9.5-iot-armhf-2018-10-07-4gb.img.xz)

Dogtag (/etc/dogtag): BeagleBoard.org Debian Image 2018-10-07 aaf2efea3f93bd31684e69bd28598327

Had to modify /boot/uEnv.txt:
```
29c29
< disable_uboot_overlay_video=1
---
> #disable_uboot_overlay_video=1
34,38d33
< 
< ###Lorank8 SPI0
< dtb_overlay=/lib/firmware/BB-SPIDEV0-00A0.dtbo
< ###
< 
```

Resulted in: 
`Kernel command line: console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet`

But failed to start `poly_pkt_fwd` due to SPI malfunctions :-(

**Comment by devlaam** [comment]
Try  bone-debian-9.3-lxqt-armhf-2018-01-28-4gb.img and version 0.2.8 or 0.2.9 (just released)

**Comment by abhatikar** [comment]
@devlaam I have the Lorank8 and the BBG in it had some issues. So I ordered a new BBG. Could you please help how can I set up the software on the new one  ? I see some scripts in the repo to install it, but any guidance would be really helpful. Thanks in advance.

**Comment by devlaam** [comment]
Hi abhatikar, this issue is closed. Please read the scripts and make an educated guess first. Experiment and have some fun. If you run into a specific problem, please open a new issue for that.
